### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by finalpi** [noes14155/Telegrambot-with-GPT4free#30]
When I asked the bot the following question, he reported an error:

> Use java to generate a hello world code

> ⏳ Hang on a sec...

The following is the log printed by docker:
```
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-95' coro=<Dispatcher._process_polling_updates() done, defined at /usr/local/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=IndexError('list index out of range')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/./main.py", line 155, in chat_handler
    response = await service.chat(call=call)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bot_service.py", line 220, in chat
    result, plugin_name = await self.ws.generate_query(text, self.plugins_dict)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bot/web_search.py", line 85, in generate_query
    plugin_name = plugin_parts[0]
                  ~~~~~~~~~~~~^^^
IndexError: list index out of range
```

**Comment by noes14155** [comment]
Fixed with the new commit. please check
