### ISSUE TITLE
Error when running the bot

### ISSUE THREAD

**Issue by MLNekit** [noes14155/Telegrambot-with-GPT4free#5]
I installed all the tokens, but for some reason when it starts it swears at some username

`PS D:\Data\Downloads\Telegrambot-with-GPT4free-master> python main.py
C:\Users\andre\AppData\Local\Programs\Python\Python311\Lib\site-packages\whisper\timing.py:57: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit
2023-06-19 16:02:11,264 (asyncio_helper.py:103 MainThread) ERROR - TeleBot: "Unknown error: AttributeError"
Traceback (most recent call last):
  File "D:\Data\Downloads\Telegrambot-with-GPT4free-master\main.py", line 220, in <module>
    asyncio.run(bot.polling())
  File "C:\Users\andre\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\andre\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\andre\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\async_telebot.py", line 306, in polling
    await self._process_polling(non_stop, interval, timeout, request_timeout, allowed_updates)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\async_telebot.py", line 399, in _process_polling
    logger.info('Starting your bot with username: [@%s]', self.user.username)
                                                          ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'username'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000237B4111B90>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x00000237B3FE2E40>, 390.218)]']
connector: <aiohttp.connector.TCPConnector object at 0x00000237B395E310>`

**Comment by noes14155** [comment]
You have an invalid bot token. please check your token file. Use the new version I have added logging
